version: '3.8'

services:
  app:
    build: .
    container_name: shorturl_app
    ports:
      - "${PORT:-8080}:8080" # Usa a porta do .env ou 8080 se não houver
    depends_on:
      - mongodb
      - redis
    environment:
      # Variáveis do Spring
      - MONGO_URI=mongodb://mongodb:27017/shorturl_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      # Variáveis Customizadas (Adicionadas para controle total)
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
      - CACHE_TTL_HOURS=${CACHE_TTL_HOURS:-24}
      - RATE_LIMIT_CAPACITY=${RATE_LIMIT_CAPACITY:-20}
      - RATE_LIMIT_TOKENS=${RATE_LIMIT_TOKENS:-20}
      - RATE_LIMIT_MINUTES=${RATE_LIMIT_MINUTES:-1}
    networks:
      - shorturl-network

  mongodb:
    image: mongo:latest
    container_name: shorturl_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - shorturl-network

  redis:
    image: redis:alpine
    container_name: shorturl_redis
    ports:
      - "6379:6379"
    networks:
      - shorturl-network

volumes:
  mongo_data:

networks:
  shorturl-network:
    driver: bridge